import './globals.css';
import Nav from '@/components/Nav';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='bg-blue-900 min-h-screen flex'>
          <Nav />
          <div className='bg-white flex-grow p-5 rounded-lg'>{children}</div>
        </main>
      </body>
    </html>
  );
}
